### ISSUE TITLE
Fehler beim Aufruf von Lineage, wenn der Sammelkorb leer ist

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-cce#1]
Ich hatte etwas im Sammelkorb und bin auf die weiterführende Aktion gegangen. Als ich später zurück kam, war die Anmeldung abgelaufen, also neu angemeldet. Dann die Aktion "Lineage" ausgelöst und es kam die folgende Fehlermeldung, da inzwischen der Sammelkorb wg. Neuanmeldung geleert worden war.
```
Undefined array key "Individual" …/modules_v4/huhwt-cce/ClippingsCartEnhanced.php:1069
#0 …/modules_v4/huhwt-cce/ClippingsCartEnhanced.php(1069): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/modules_v4/huhwt-cce/ClippingsCartEnhanced.php(916): HuHwt\WebtreesMods\ClippingsCartEnhanced\ClippingsCartEnhanced->cceDownloadAction()
#2 …/app/Http/RequestHandlers/ModuleAction.php(85): HuHwt\WebtreesMods\ClippingsCartEnhanced\ClippingsCartEnhanced->postExecuteAction()
#3 …/app/Http/Middleware/RequestHandler.php(54): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()
#4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
```

**Comment by huhwt** [comment]
Stelle gefunden, Fehler tritt nicht mehr auf (Kontrolle, ob was im Korb ist davorgesetzt) - wird mit dem nächsten Release gefixt.

**Comment by hartenthaler** [comment]
fein
