### ISSUE TITLE
Error in dev version when using Vesta modules

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-cce#18]
When opening the Vesta list menu "Individuals with Patriarchs" there is an error:

```
View file not found: …/app/../resources/views/lists/CCEsurnames-table.phtml …/app/View.php:260
#0 …/app/View.php(183): Fisharebest\Webtrees\View->getFilenameForView()
#1 …/app/View.php(278): Fisharebest\Webtrees\View->render()
#2 …/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make()
#3 …/modules_v4/vesta_extended_relationships/IndividualListModule_2_1_16.php(396): view()
#4 …/modules_v4/vesta_extended_relationships/ExtendedIndividualListRequestHandler.php(81): Cissee\Webtrees\Module\ExtendedRelationships\IndividualListModule_2_1_16->createResponse()
```

**Comment by hartenthaler** [comment]
After updating Vesta modules: no error.

**Comment by ric2016** [comment]
In any case should be resolved (from Vesta side anyway) after code cleanup [here](https://github.com/vesta-webtrees-2-custom-modules/vesta_extended_relationships/issues/121).

**Comment by hartenthaler** [comment]
In my opinion, this issue can be closed now.
