### ISSUE TITLE
Fehlverhalten nach Timeout

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-cce#23]
Nachdem ich durch Timeout abgemeldet worden bin, habe ich mich neu angemeldet. Es wurde angezeigt, dass der Sammelbehälter nun leer ist. Dennoch wurde die Option zur Übertragung an die Tag-Verwaltung angezeigt. Nach dem Klick darauf kam die folgende Fehlermeldung:
```
Undefined array key 1 …/modules_v4/huhwt-tsm/TaggingServiceManager.php:407
#0 …/modules_v4/huhwt-tsm/TaggingServiceManager.php(407): Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}()
#1 …/app/Http/RequestHandlers/ModuleAction.php(85): HuHwt\WebtreesMods\TaggingServiceManager\TaggingServiceManager->getTaggingServiceAction()
#2 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\ModuleAction->handle()
#3 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
```

**Comment by huhwt** [comment]
Die Option sollte bei leerem Sammelbehälter nicht gezeigt werden ... allerdings läuft es dann bei mir (local und hoster) nicht in einen PHP-Error, sondern es gibt nur Javascript-Errors, welche auch nur dann auffallen, wenn die Browser-Dev-Tools geöffnet sind; die Seite sieht dann aber wie erwartet aus. Das Verhalten nach Timeout habe ich nicht geprüft, wenn das mal passiert ist, habe ich immer erst den Sammelbehälter gefüllt ...
