### ISSUE TITLE
scandir(): Argument #1 ($directory) must be of type string, null given

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-cce#28]
scandir(): Argument #1 ($directory) must be of type string, null given …/modules_v4/huhwt-cce/ClippingsCartEnhancedModule.php:256
#0 …/modules_v4/huhwt-cce/ClippingsCartEnhancedModule.php(256): scandir()
#1 …/modules_v4/huhwt-cce/ClippingsCartEnhancedModule.php(125): HuHwt\WebtreesMods\ClippingsCartEnhanced\ClippingsCartEnhancedModule->doCartLoad()

Ich stand auf der Anzeige eines leeren Sammelbehälters. Dann wurde ich wegen Timeout ausgeloggt. Dann habe ich das Kopieren einer Datei in den Sammelbehälter angeklickt und die Fehlermeldung erschien, da ich nicht mehr angemeldet war.

**Comment by huhwt** [comment]
Da muss ich noch nacharbeiten.

**Comment by hartenthaler** [comment]
Never occured again.
